Init: Randomized Quasi Monte Carlo Method
Engelsgeduld/PySATL_NMVM_Module pull request #4
Opened 2024-07-19 11:06 UTC by Engelsgeduld

2024-07-19 12:39 UTC, vkutuev requested changes

2024-07-19 12:39 UTC, vkutuev commented on .gitignore
> +.hypothesis
Add newline at the end of file

2024-07-19 17:54 UTC, Desiment requested changes

2024-07-19 17:54 UTC, Desiment commented on src/algorithms/support_algorithms/rqmc.py
> +        sample = np.random.rand(self.count, self.base_n)
Получающийся таким образом sample имеет равномерное распределение на [0;1], это не тоже самое что последовательность Соболя:
https://en.wikipedia.org/wiki/Sobol_sequence
Отсюда и проблемы с точностью

Здесь sample необходимо брать как матрицу с одинаковыми строчками, где каждая строчка состоит из элементов последовательности Соболя с номерами  1, ...self.base_n. После чего генерировать self.count независимых случайных величин U_1, .... U_B с равномерным распределением на отрезке [0; 1]  и i-ую строчку матрицы sample XOR-ить с U_i  (это и есть digital shift)

2024-07-19 17:54 UTC, Desiment commented on src/algorithms/support_algorithms/rqmc.py
> +        return approximation
Стоит возвращать также и current_error_tolerance

2024-07-19 17:54 UTC, Desiment commented on src/algorithms/support_algorithms/rqmc.py
> +            sample = np.random.rand(self.count, self.base_n * i)
Опять же, здесь sample необходимо брать как матрицу с одинаковыми строчками, где каждая строчка состоит из элементов последовательности Соболя с номерами 
- начиная с (self.base_n - 1) * i
- заканчивая self.base_n * (i + 1)

После чего генерировать self.count независимых случайных величин U_1, .... U_B с равномерным распределением на отрезке [0; 1]  и i-ую строчку матрицы sample XOR-ить с U_i

2024-07-23 15:56 UTC, vkutuev commented on src/algorithms/support_algorithms/rqmc.py
> +from numba import njit
А точно numba уже нужна?

2024-07-23 15:56 UTC, vkutuev commented on src/algorithms/support_algorithms/rqmc.py
> +    def _args_parse(error_tolerance: float, count: int, base_n: int, i_max: int, a: float) -> None:
На парсинг не тянет, это скорее валидация

2024-07-29 07:58 UTC, vkutuev approved these changes

2024-07-29 23:52 UTC, merged